quarkus.mailer.from=test@mailtrap.io
quarkus.mailer.host=sandbox.smtp.mailtrap.io
quarkus.mailer.port=2525
quarkus.mailer.start-tls=OPTIONAL
quarkus.mailer.username=75f0fdab94ddec
quarkus.mailer.password=995b5bce4d0fea
quarkus.mailer.mock=false




quarkus.http.port=9090

quarkus.log.level=DEBUG
quarkus.log.console.level=DEBUG
quarkus.log.category."io.vertx.ext.mail".level=DEBUG
quarkus.log.category."io.quarkus.mailer".level=DEBUG
quarkus.log.category."io.vertx".level=DEBUG

