quarkus.http.port=9090

quarkus.log.level=INFO
%dev.quarkus.log.level=DEBUG
%dev.quarkus.log.category."io.quarkus.mailer".level=DEBUG

%dev.quarkus.mailer.from=test@mailtrap.io
%dev.quarkus.mailer.host=sandbox.smtp.mailtrap.io
%dev.quarkus.mailer.port=2525
%dev.quarkus.mailer.start-tls=OPTIONAL
%dev.quarkus.mailer.username=75f0fdab94ddec
%dev.quarkus.mailer.password=995b5bce4d0fea

%prod.quarkus.mailer.from=${MAILER_FROM}
%prod.quarkus.mailer.host=${MAILER_HOST}
%prod.quarkus.mailer.port=${MAILER_PORT:587}
%prod.quarkus.mailer.start-tls=${MAILER_START_TLS:REQUIRED}
%prod.quarkus.mailer.username=${MAILER_USERNAME}
%prod.quarkus.mailer.password=${MAILER_PASSWORD}

%test.quarkus.mailer.mock=true
